AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS Lambda Adapter (x86_64) - Run web applications on AWS Lambda

Resources:
  LambdaAdapterLayerX86:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: .
      CompatibleRuntimes:
        - nodejs16.x
        - nodejs14.x
        - nodejs12.x
        - python3.9
        - python3.8
        - python3.7
        - ruby2.7
        - java11
        - java8.al2
        - java8
        - go1.x
        - dotnet6
        - dotnetcore3.1
        - provided.al2
        - provided
      Description: 'Layer for AWS Lambda Adapter x86_64'
      LicenseInfo: 'Available under the Apache-2.0 license.'
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: makefile
      BuildArchitecture: x86_64

  LayerVersionPermission:
    Type: AWS::Lambda::LayerVersionPermission
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref LambdaAdapterLayerX86
      Principal: '*'

  LambdaAdapterLayerX86Parameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /lambda-web-adapter/layer/x86_64/latest
      Description: 'Layer ARN for the latest Lambda Web Adapter X86_64 Layer'
      Type: String
      Value: !Ref LambdaAdapterLayerX86

Outputs:
  LambdaAdapterLayerX86Arn:
    Description: "arn for LambdaAdapterLayerX86"
    Value: !Ref LambdaAdapterLayerX86
