AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS Lambda Adapter (Arm64) - Run web applications on AWS Lambda

Parameters:
  CargoPkgVersion:
    Type: String
    Default: latest

Resources:
  LambdaAdapterLayerArm64:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: .
      CompatibleArchitectures:
        - arm64
      Description: !Sub 'Layer for AWS Lambda Adapter arm64: ${CargoPkgVersion}'
      LicenseInfo: 'Available under the Apache-2.0 license.'
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: makefile
      BuildArchitecture: arm64

  LayerVersionPermission:
    Type: AWS::Lambda::LayerVersionPermission
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref LambdaAdapterLayerArm64
      Principal: '*'

  LambdaAdapterLayerArm64Parameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /lambda-web-adapter/layer/arm64/latest
      Description: 'Layer ARN for the latest Lambda Web Adapter Arm64 Layer: latest'
      Type: String
      Value: !Ref LambdaAdapterLayerArm64

  LambdaAdapterLayerArm64VersionParameter:
    Type: AWS::SSM::Parameter
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !Sub '/lambda-web-adapter/layer/arm64/${CargoPkgVersion}'
      Description: !Sub 'Layer ARN for the latest Lambda Web Adapter Arm64 Layer: ${CargoPkgVersion}'
      Type: String
      Value: !Ref LambdaAdapterLayerArm64

Outputs:
  LambdaAdapterLayerArm64Arn:
    Description: "arn for LambdaAdapterLayerArm64"
    Value: !Ref LambdaAdapterLayerArm64
