version: '3.8'

services:
  webserver:
    build: .
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./app:/var/task/app
      - ./nginx/conf/nginx.conf:/opt/nginx/conf/nginx.conf
