AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Ruby 3.3.0

  Sample SAM Template for Sinatra app.

Globals:
  Function:
    Timeout: 60

Resources:
  SinatraFunction1:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 512
      Architectures:
        - x86_64
      Timeout: 30
      FunctionUrlConfig:
        AuthType: NONE
    Metadata:
      DockerTag: latest
      DockerContext: ./app
      Dockerfile: Dockerfile

Outputs:
  SinatraFunction1:
    Description: "Function URL endpoint on AWS Lambda"
    Value: !GetAtt SinatraFunction1Url.FunctionUrl

