AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.12

  Sample SAM Template for FastHTML

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  FastHTMLFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 256
      Events:
        ApiEvents:
          Type: HttpApi
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./app
      DockerTag: python3.12-v1

Outputs:
  FastHTMLURL:
    Description: "API Gateway endpoint URL for Prod stage for FastHTML function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/"
  FastHTMLFunction:
    Description: "FastHTML Lambda Function ARN"
    Value: !GetAtt FastHTMLFunction.Arn
  FastHTMLIamRole:
    Description: "Implicit IAM Role created for FastHTML function"
    Value: !GetAtt FastHTMLFunctionRole.Arn
