AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bedrock-agent-fastapi

  FastAPI app that work with Agents for Amazon Bedrock

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  BedrockAgentFastAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./app
      Runtime: python3.12
      Handler: run.sh
      MemorySize: 1024
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/bootstrap
          AWS_LWA_READINESS_CHECK_PROTOCOL: TCP
          PORT: 8000
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:753240598075:layer:LambdaAdapterLayerX86:20 
      Policies: AmazonS3ReadOnlyAccess

  BedrockAgentPermission:  
    Type: AWS::Lambda::Permission  
    Properties:  
      FunctionName: !Ref BedrockAgentFastAPIFunction  
      Action: lambda:InvokeFunction  
      Principal: bedrock.amazonaws.com  
      SourceAccount: !Ref 'AWS::AccountId'  
      SourceArn: !Sub arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:agent/*  

Outputs:  
  BedrockAgentFastAPIFunction:  
    Description: "BedrockAgentFastAPIFunction Lambda Function ARN"  
    Value: !GetAtt BedrockAgentFastAPIFunction.Arn  
